(ns ariane.atom
  "Namespace for parsing Atom feeds.")

(defn parse-atom
  "Parse Atom feed generated by ariane.core/parse"
  [feed]
  (for [tag feed]
    (let [tag-name (:tag tag)
          tag-content (:content tag)]
      (cond
       (= tag-name :subtitle) [:description (first tag-content)]
       (= tag-name :summary) [:description (first tag-content)]
       (= tag-name :link) [:link (get-in tag [:attrs :href])]
       (= tag-name :author) [:author (parse-atom (:content tag))]
       (= tag-name :entry) [:item (parse-atom (:content tag))]
       :else [tag-name (first tag-content)]))))
