(ns ariane.rss
  "Namespace for parsing RSS feeds.")

(defn- channel
  [feed]
  (:content (first feed)))

(defn- parse-feed
  [feed]
  (for [tag feed]
    (let [tag-name (:tag tag)
          tag-content (:content tag)]
      (cond
       (= tag-name :guid) [:id (first tag-content)]
       (= tag-name :lastBuildDate) [:updated (first tag-content)]
       (= tag-name :pubDate) [:published (first tag-content)]
       (= tag-name :author) [:author (parse-feed (:content tag))]
       (= tag-name :item) [:item (parse-feed (:content tag))]
       :else [tag-name (first tag-content)]))))

(defn parse-rss
  "Parse RSS feed generated by ariane.core/parse"
  [feed]
  (-> feed 
      channel
      parse-feed))